// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nncjnqrosthnhrbouruh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5uY2pucXJvc3RobmhyYm91cnVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2Mjk3MjgsImV4cCI6MjA1ODIwNTcyOH0.vtusxbPXWodWm-fpy37wRoxTo5AnmG9s5ekCO4dNKpY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);